Automatización de salida gráfica de consulta - Pasos 12 al 14
Proyecto-Mandarina/salidagrafica-atlas pull request #1
Opened 2021-10-27 17:45 UTC by ajcappo

Se modificó el código para automatizar los puntos 12, 13 y 14 que figuran en:
https://github.com/Proyecto-Mandarina/salidagrafica-atlas/blob/master/salida-gr%C3%A1fica%20atlas%20instructivo.pdf

2021-10-31 22:40 UTC, hernan-alperin requested changes
podés procesar el csv para que queda más prolijo?
o mejor aún, hacer un sql para
crear una tabla
colores_segmentos
con campos
segmento, color,  line_color, outline_color
?

2021-11-01 11:55 UTC, hernan-alperin requested changes
está bien. pero fijate que name debe llamarse segmento debe ser clave única, vos introducís 1 registro por cada linea del csv cuando lo ideal es sumarizarlas.

¿podés escribir un SQL que haga eso?
segmento, color, line_color, outline_color
con segmento sin repetirse y con ningún campo en ''

para ello quizás te sirva usar una postgres DB propia

2021-11-01 12:55 UTC, ajcappo commented
> está bien. pero fijate que name debe llamarse segmento debe ser clave única, vos introducís 1 registro por cada linea del csv cuando lo ideal es sumarizarlas.
> 
> ¿podés escribir un SQL que haga eso? segmento, color, line_color, outline_color con segmento sin repetirse y con ningún campo en ''
> 
> para ello quizás te sirva usar una postgres DB propia

Cambiar el name por segmento si, pero para unificar cada segmento con los estilos de colores en algunos casos va a haber problema, porque algunos segmentos tienen 2 estilos de algún color ( color, line_color, outline_color).
Por ejemplo el segmento 10:

('10', '', '', '172,54,240,0'),
('10', '', '', '255,255,255,255'),
('10', '', '172,54,240,255', ''),
('10', '', '255,0,0,255', ''),
('10', '172,54,240,255', '', ''),
con 2 outile_color, 2 color y 1 line_color

2021-11-02 00:28 UTC, merged

2021-11-02 00:28 UTC, hernan-alperin commented
corregir redundancias en el segmento 10